# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy angular frontend

on:
  push:
    paths: "./frontend"
  pull_request:
    paths: "./frontend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
      
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22.x'

      - name: configure github pages
        uses: actions/configure-pages@v5.0.0
        
      - name: install dependencies
      - run: npm install --legacy-peer-deps
        working-directory: "./frontend"

      - name: build project
      - run: npm build
        working-directory: "./frontend"

      - name: upload artifacts
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./frontend/dist/re-view/browser"

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        
